### ISSUE TITLE
List of communities

### ISSUE THREAD

**Issue by rekonchik** [Dementiy/vkR#11]
Будет ли реализация поиска сообществ по тегам, тематике? Появится ли возможность отображать статусы сообществ (открытое/закрытое, официальное, сообщество-встреча и т.д.)?

**Comment by Dementiy** [comment]
`getGroupsById()` позволяет получить информацию об указанных сообществах. Добавил функцию `groupsSearch()`, которая позволяет искать сообщества по заданному критерию.
