### ISSUE TITLE
Ошибка при получении комментариев

### ISSUE THREAD

**Issue by maximgalchenko** [Dementiy/vkR#17]
Действую по https://vk.com/doc-89201406_442504700?dl=cf6aecc195b7a42c68.
Создаю объект wall и пытаюсь выполнить:
comments_list <- lapply(wall, vkR::wallGetCommentsList, progress_bar = TRUE)
После выкачивания (бар на 100%) получаю:
Ошибка в posts$comments :$ operator is invalid for atomic vectors
Пакет:
Package: vkR
Type: Package
Title: Access to VK API via R
Description: Provides an interface to the VK API <https://vk.com/dev/methods>.
      VK <https://vk.com/> is the largest European online social networking
      service, based in Russia.
Version: 0.1
Date: 2016-12-01

**Comment by Dementiy** [comment]
Не совсем понимаю откуда взялась переменная `posts`. Давайте я пример приведу, например, есть две группы:
```
> groups <- c('habr', 'postnauka')
```

Для каждой группы получим по две записи со стены:
```
> wall_list <- lapply(groups, function(group) vkR::getWallExecute(domain=group, count=2, progress_bar=T))
  |=============...=================| 100%
  |=============...=================| 100%
```

И для каждой стены получим комментарии:
```
> cmnts_list <- lapply(wall_list, vkR::wallGetCommentsList, progress_bar=T)
  |=============...=================| 100%
  |=============...=================| 100%
```

Комментарии к стене первой группы можно получить по индексу 1, а ко второй группе по индексу 2:
```
> cmnts_lists[[1]]
$`1004194`
       id   from_id       date ...
1 1004303 236892217 1491329059 ...
2 1004307  14856154 1491329572 ...
```

Где `1004194` это идентификатор поста со стены первой группы. Мы получали по две записи для каждой стены, соответственно:
```
> names(cmnts_lists[[1]])
[1] "1004194" "1006167"
> names(cmnts_lists[[2]])
[1] "191677" "191797"
```

Надеюсь, что ответил на вопрос

**Comment by maximgalchenko** [comment]
Спасибо, но у нас с Вами одинаковый уровень непонимания относительно posts. 
Я работаю пока с одной группой, ориентируюсь на Вашу отлично (без сарказма) оформленную справку и материалы к пакету.
Вот мой код:
```
library(vkR)
library(stringr)
library(tm)
library(SnowballC)
library(wordcloud)
library(RColorBrewer)

vkOAuth(client_id = 12345678, scope = "wall") # Убрал логин и пароль
at <- getAccessToken()
me()
wall <- getWallExecute(domain='anonimgau', count=0, filter = "all", progress_bar=TRUE)
wall_posts <- wall #Подумал, а вдруг что-то не так с именем переменной, поэтому сделал переприсвоение
comments_list <- lapply(wall_posts, vkR::wallGetCommentsList, progress_bar = TRUE)
posts <- wall$posts
```

Итог: 
```
>  comments_list <- lapply(wall_posts, vkR::wallGetCommentsList, progress_bar = TRUE)
  |=========...===================================================================| 100%
Ошибка в posts$comments :$ operator is invalid for atomic vectors
```
Проблема остаётся. Что не так? Кстати, в описании wallGetCommentsList(**posts**, progress_bar = FALSE, v = getAPIVersion())

**Comment by Dementiy** [comment]
Если я правильно понимаю, то проблема в том, что вы применяете `lapply()` не к списку, а к одному объекту. Попробуйте так (на примере 10 записей со стены):

```
> wall <- getWallExecute(domain='anonimgau', count=10, filter = "all", progress_bar=TRUE)
> comments <- wallGetCommentsList(wall, progress_bar=T)
> head(comments)
$`4170`
    id  from_id       date                                                                            text
1 4172  9559326 1491244044 Ппц я тут в Пулково сижу, одним днём прилетели и обратно жесть канешь\U0001f62c
2 4173 23347095 1491244403                                              Всё очень очень грустно \U0001f622
...
```

А если есть список стен с разных групп, то тогда можно делать как было описано выше.
