### ISSUE TITLE
getUsersExecute- кодировка+сервисный ключ

### ISSUE THREAD

**Issue by yurasik2000** [Dementiy/vkR#18]
Во-первых, хочу сказать спасибо за библиотеку!

Заметил несколько непоняток:
1. Функция getUsersExecute возвращает кракозябры в кириллице, а между тем как, например, метод getGroupsMembers выдает все в читаемом виде. Попытка применить iconv в разных вариациях не помогла. 
http://prntscr.com/eyd9a7

2.  Функция getUsersExecute не работает с сервисным ключом доступа, хотя такая возможность указана в документации https://vk.com/dev/users.get. (Устаревший метод getUsers позволяет использовать сервисный ключ)

Кстати, пока и users.get и groups.getMembers работают вообще без токенов. Хотя ВК и обещает это изменить в скором времени. Возможно нужно сделать возможность использовать эти методы и без проверки авторизации. Работа без авторизации позволяет избежать ограничения на вызов апи макс 3 раза/сек.

3. Не удалось запустить код из примера Building a Friend Graph
http://prntscr.com/eydf95

**Comment by Dementiy** [comment]
Что касается `getUsersExecute()`, то эта функция построена на методе `execute()`, который можно вызвать либо с ключом доступа пользователя, либо с ключом доступа сообщества ([https://vk.com/dev/execute](https://vk.com/dev/execute)).
Метод `getUsers()` не требует токена, но выдает предупреждение о том, что метод устаревший и вызывается без токена доступа (можно не обращать внимания):
```
> getUsers(user_ids = 1)
  id first_name   last_name hidden
1  1      Павел     Дуров
Warning message:
'getUsers' is deprecated.
Use 'getUsersExecute()' instead.
See help("Deprecated") 
```
Но, если токен доступа до этого использовался и истек, то его нужно сбросить, чтобы истекший токен не подставлялся в запрос (я поправлю, чтобы при истечении токена он сбрасывался бы автоматически):
```
setAccessToken() # Без аргументов
```

По поводу "кракозябр". Я предполагаю, что пакет установлен на Windows. Мне к сожалению эту проблему пока не воспроизвести. Могу пока предложить попробовать такое решение:
```
> options(encoding = "UTF-8")
```

Что касается графа, пример рабочий, если подгружен пакет `dplyr` :) Я поправлю документацию. Можете попробовать так:
```
my_friends <- my_friends$items[is.na(my_friends$items$deactivated), ] 
network <- getNetwork(my_friends$id)
```

**Comment by yurasik2000** [comment]
> Метод getUsers() не требует токена,

Да, действительно. Спасибо. Я просто испугался, что он "Deprecated" и больше с ним не экспериментировал :) 

> По поводу "кракозябр". Я предполагаю, что пакет установлен на Windows. 

Да, на Windows.  И да, там проблема с кодировкой консоли распостранена. Но вся фишка в том, что другая Ваша ф-ция getGroupsMembers все выдает нормально. Так, что, возможно, проблема не в Windows. 
options(encoding = "UTF-8") - не помогло :( 

> Что касается графа, пример рабочий, если подгружен пакет dplyr

Не помог ни dplyr, ни по  другому сделанная индексация

```
library("dplyr") 
my_friends <- getFriends(fields = 'sex')
my_friends <- filter(my_friends$items, is.na(deactivated))
Error in filter_impl(.data, dots) : object 'deactivated' not found

my_friends <- my_friends$items[is.na(my_friends$items$deactivated), ]
Warning message:
In is.na(my_friends$items$deactivated) :
is.na() applied to non-(list or vector) of type 'NULL'

network <- getNetwork(my_friends$id)
Error: VK API request failed
VK error message [100]: One of the parameters specified was missing or invalid: target_uid not integer
```
И главная проблема, видимо, даже не в deactivated (у меня в друзьях их просто нет), а дальше, в getNetwork.

**Comment by Bugamed** [comment]
Присоединяюсь к проблеме с кодировкой, декодеры определяют эти кракозябры как win-1251 => UTF-8
причем сам шелл считает, что всё нормально, и всё в UTF-8 уже считается

**Comment by Bugamed** [comment]
С кодировкой разобрался методом тупого перебрасывания туда-обратно
Мне помогла конвертация UTF-8 => CP1251, после которой UTF-8 => windows-1251
то есть, код такой:
```R
 x = iconv(x, 'UTF-8', 'CP1251')
 x = iconv(x, 'UTF-8', 'windows-1251')
```

**Comment by yurasik2000** [comment]
Видимо это не корректно отрабатывает функция  jsonlite::fromJSON. Там даже был похожий баг-репорт: https://github.com/jeroen/jsonlite/issues/42 Но как-то он затух.

Мне шаманство с перебрасываниями кодировок тоже помогло. Спасибо @Bugamed 
Но хотелось бы чего-то поизящнее )

**Comment by Bugamed** [comment]
Согласен, дело нудное и неудобное, но, хотя бы работает.

**Comment by Dementiy** [comment]
К сожалению не могу воспроизвести проблему, так как тестирую только на Unix-like операционных системах. Я могу попробовать на уровне пакета сделать перекодировку (костыль) с помощью `iconv` для Windows, если опишите шаги, которые выполняете для перекодировки.
Еще можно попробовать изменить локаль: `Sys.setlocale(locale = "Russian")`

**Comment by yurasik2000** [comment]
@Dementiy,
`Sys.setlocale(locale = "Russian")` не помогает. Как я уже писал, судя по Вашему коду, мое мнение, что косячит сама функция `jsonlite::fromJSON`.  Только остается загадкой, почему в одних Ваших методах, даже похожих, она отрабатывает нормально, а в других нет. Вам, как разработчику, разобраться будет проще )

Для понимания (список не полный)
1. Нет проблем с кодировкой: `getGroupsMembers, getFriends`
2. Есть проблемы с кодировкой: `getGroupsMembersExecute, usersGetFollowers, getUsers, getUsersExecute`

Шаги по перекодировке (костыль) описал @Bugamed. Два раза сделать iconv. Уж не знаю, стоит ли его вставлять на уровне пакета )

**Comment by Dementiy** [comment]
Обновите пакет с github'а и попробуйте проверить методы, которые заканчиваются на Execute (например, `getUsersExecute`) и напишите останутся ли проблемы с кодировкой?

**Comment by yurasik2000** [comment]
@Dementiy,
У методов getUsersExecute, getGroupsMembersExecute и даже usersGetFollowers проблем с кодировкой под Windows-ом нет! Спасибо, Дмитрий! ) 
Другие методы пока не смотрел.

Единственно, постоянно ругается варнингами:
Warning message:
'jsonlite::rbind.pages' is deprecated.
Use 'rbind_pages' instead.
See help("Deprecated")

По багу #19 проблема решилась, но не до конца. Написал комментарии в ту ветку.

**Comment by Dementiy** [comment]
С кодировкой больше проблем быть не должно.

Что касается предупреждений, то в пакете `jsonlite` функция `rbind.pages` была переименована в `rbind_pages`, а `rbind.pages` теперь считается устаревшей. Я через некоторое время внесу изменения и поправлю все места где вызывается `rbind.pages`, тогда предупреждений больше не будет.

А более серьезные изменения в пакете vkR будут скорее всего в конце лета.
