### ISSUE TITLE
usersGetFollowers - дубликаты в выдаче (очень много)

### ISSUE THREAD

**Issue by yurasik2000** [Dementiy/vkR#19]
В выдаче функции большая часть фолловеров продублированы по нескольку раз. Хотя суммарное число выданных  фолловеров = заявленному во ВКонтакте. 

```
library("vkR")
library(data.table)
library(magrittr)

# получаем подписчиков Филиппа Киркорова )))
followers <- usersGetFollowers(273251945, fields='sex,bdate', flatten=TRUE)
followers <- followers$followers
dim(followers)
[1] 93237     6   # совпадает с заявленным числом поклонников Бедросовича в  ВК :)

# проверяем на уникальность по id
dim(subset(followers, duplicated(id))) 
[1] 62236     6  # это все дубли!
dim(subset(followers, !duplicated(id)))
[1] 31001     6  # это уникальные фолловеры

# выведем дубликаты для контроля просортировав их по id
test_duplicate <- subset(followers, duplicated(id))
head(test_duplicate[order(test_duplicate[,1]),], n=10)
         id first_name last_name sex      bdate deactivated
37370 26564    Татьяна    Зорьян   1 30.12.1987        <NA>
59370 26564    Татьяна    Зорьян   1 30.12.1987        <NA>
81370 26564    Татьяна    Зорьян   1 30.12.1987        <NA>
69280 69567     Оксана Плешакова   1   2.5.1986        <NA>
91280 69567     Оксана Плешакова   1   2.5.1986        <NA>
37153 88085       Илья   Босенок   2       <NA>        <NA>
59153 88085       Илья   Босенок   2       <NA>        <NA>
81153 88085       Илья   Босенок   2       <NA>        <NA>
41739 91863  Анастасия  Семенова   1  30.8.1984        <NA>
63739 91863  Анастасия  Семенова   1  30.8.1984        <NA>

# альтернативный скрипт вывода уникальных id
test_duplicate <- as.data.table(followers) %>% setkey(id) %>% unique
dim(test_duplicate)
[1] 31001     6
```

**Comment by kozhushman** [comment]
Не подскажешь, как ты смог получить выходные данные в кириллице?
Я просто что ни пробовал, так и не получилось.
Ось вин или линукс?

**Comment by Dementiy** [comment]
Проблему увидел. В ближайшее время постараюсь решить

**Comment by yurasik2000** [comment]
@kozhushman,
Ось вин. Выходные данные в кириллице можно получить с помощью костыля, описанного в соседней ветке #18.  Я для себя отдельную функцию написал. Ее нужно применять ко всем данным с битой кодировкой.
```
library(magrittr)
# функция для исправления битой кодировки в Windows
winCode <- function(x){
  y <- x %>% iconv('UTF-8','CP1251') %>% iconv('UTF-8','windows-1251')
  return(y)
}

# исправляем кодировки в текстовых полях
followers$first_name <- winCode(followers$first_name)
followers$last_name <- winCode(followers$last_name)

```

**Comment by kozhushman** [comment]
Благодарю

**Comment by yurasik2000** [comment]
@Dementiy,

После исправлений исчезла основная проблема - огромное количество дублей  в выдаче,  спасибо!
Но:
Иногда, при довольно большом количестве подписчиков (конкретно в моем опыте ~300К) в выдаче появляются 2-3 дубля. 
Особенности:
1. Они не фиксированы. При новом запросе подписчиков к тому же пользователю дубли могут быть совершенно разные.
2. При одинаковых запросах их количество плавает. (у меня 1-3)
3. Они идут подряд (см. пример)
4. Их порядковый номер начинается с 1.

Примеры (запрос один и тот же):
1. 
 ```
            id first_name
100001 999754        Еша  
100002 999754        Еша  

44001 199390905     Володя
44002 199390905     Володя

12001 173357391    Дмитрий
12002 173357391    Дмитрий

```
2. 
```
             id first_name
94001 408343615      Расул
94002 408343615      Расул

204001 215938614    Татьяна
204002 215938614    Татьяна
```

**Comment by Dementiy** [comment]
Нужны идентификаторы пользователей для воспроизведения проблемы. Можно отправить на почту, если не хочется публиковать тут.

**Comment by yurasik2000** [comment]
@Dementiy, я брал случайных пользователей из топа по количеству подписчиков, и проблемы были у всех. Ну, например:
id32707600 (два дубля, id376031974, id99272844)
id301419447 (1 дубль, id23060066)

Как я уже писал, результаты при одинаковых запросах - разные. Как по количеству дублей, так и по их id. Единственная закономерность, которую я заметил, что а) количество повторов одного id всегда ровно два, б) их порядковые номера начинаются с единицы, типа 72001, 72002.

**Comment by Dementiy** [comment]
Проблему вроде закрыл. Вот еще пример сбора подписчиков для вектора пользователей (если будет работать нормально, то включу в пакет): [https://gist.github.com/Dementiy/c23053ef0fdaf6ec90860c2a996ae17a](https://gist.github.com/Dementiy/c23053ef0fdaf6ec90860c2a996ae17a)
