### ISSUE TITLE
Проблема с получением access token'а

### ISSUE THREAD

**Issue by kozhushman** [Dementiy/vkR#20]
Когда я пытаюсь авторизоваться, вместо открытия окна я получаю следующую ошибку:
Ошибка в curl::curl_fetch_memory(url, handle = handle) :
  URL using bad/illegal format or missing URL
Я знаю, что curl не очень хорошо работает под виндой, но не уверен, в этом ли проблема.

**Comment by Dementiy** [comment]
Сложно сказать в чем ошибка. Как пытаетесь авторизоваться? Чтобы открылось окно браузера логин и пароль указывать не нужно.

**Comment by kozhushman** [comment]
Ох, мой косяк, прошу прощения. "omitted" в описании читал как "commited" и поэтому воспринял все неправильно.
