### ISSUE TITLE
getGroupsById ошибка при больших количествах group_ids

### ISSUE THREAD

**Issue by yurasik2000** [Dementiy/vkR#21]
Функция возвращает ошибку. (Видимо, при слишком длинной строке group_ids)

```
# тут все ок
groups_count <- getGroupsById(group_ids=paste(c(1:232), collapse = ","), fields='members_count')

# добавляем еще один group_id
groups_count <- getGroupsById(group_ids=paste(c(1:233), collapse = ","), fields='members_count')
Error: lexical error: invalid char in json text.
                                       https://api.vk.com/method/group
                     (right here) ------^
```
Ограничения контакта на максимальное число идентификаторов (500) не нарушаются.

```
# сами по себе идентификатор группы 233 ошибок не вызывает
# тут все снова ок
groups_count <- getGroupsById(group_ids=paste(c(230:235), collapse = ","), fields='members_count')

```

Надо заметить, что число 232 не является волшебным. По мере увеличения разрядности самих идентификаторов минимальное количество групп для появления ошибки уменьшается.

И, насколько я заметил, до недавнего (возможно до правки бага #18)  функция работала без ошибок при тех же условиях.

**Comment by Dementiy** [comment]
А совокупная длина строки не превышает 65 тысяч символов? Например, в `getUsersExecute` я делал ограничение на длину строки в 65 тысяч символов, иначе были проблемы с API ВК.

**Comment by yurasik2000** [comment]
@Dementiy , совсем не превышает :) Если брать мой пример, то:
```
nchar(paste(c(1:233), collapse = ","))
[1] 823

```

**Comment by Dementiy** [comment]
А можно список групп получить, чтобы я воспроизвел проблему?

**Comment by yurasik2000** [comment]
@Dementiy, я же в коде написал ) Я эмулировал список групп обычным числовым вектором превращенным в текстовую строку. 
```
group_ids=paste(c(1:232), collapse = ",") # функция отрабатывает без ошибок
group_ids=paste(c(1:233), collapse = ",") # строка на один элемент длиннее и ошибка

```
Но и с реальными id групп проблема такая же.
