### ISSUE TITLE
getGroupsMembersExecute - Error

### ISSUE THREAD

**Issue by yurasik2000** [Dementiy/vkR#23]
Трудноуловимая ошибка. Конкретный пример:
```
getGroupsMembersExecute(1, fields = 'sex,bdate,city,country,relation,last_seen')
Error: lexical error: invalid char in json text.
                                       <html>  <head><title>404 Not Fo
                     (right here) ------^
```
Подсказки: 
Ошибка появляется не всегда. Она проявляется при **сочетании** двух факторов:

а) длины переменной `fields`. Если в `fields `будет меньше параметров, то функция отработает без ошибки. Например:
`getGroupsMembersExecute(1, fields = 'sex,bdate,city') # ошибок нет`

б) количества пользователей в группе. Если группа малочисленна, то функция отработает без ошибки. Например, возьмем группу с group_id=20. (всего 4483 пользователей):
`getGroupsMembersExecute(20, fields = 'sex,bdate,city,country,relation,last_seen') # ошибок нет`

**Вывод**: по приблизительным оценкам ошибка проявляется, если в поле `fields` указаны больше трех параметров **И** размер группы больше ~50К пользователей. 

Видимо, существует некий критический объем данных. Если предпринимается попытка получить из api данные большего объема, то ошибка проявляется. Где-то ловится 404 Not Found.

P/S В методе getGroupsMembers таких ошибок не наблюдалось.

**Comment by Dementiy** [comment]
Да, ошибка в слишком большом ответе. API возвращает нестандартные ошибки, либо 404, либо 500. Добавил небольшой "костыль" - должно работать.
