### ISSUE TITLE
getGroupsForUsers и getGroupsForUsers не совпадают

### ISSUE THREAD

**Issue by rekonchik** [Dementiy/vkR#30]
Привет. Есть группа 86359614. Там есть пользователь 186726546, но почему-то когда я забираю её группы через getGroupsForUsers, то в наборе групп 86359614 нет. И такое с этой группой очень часто.  В чем причина и как с этим бороться, чтобы по пользователю получать полный набор групп?

**Comment by Dementiy** [comment]
Если тестировать через API VK, то этой группы тоже не будет. Вот [ссылка](https://vk.com/dev/groups.get?params[user_id]=186726546&params[extended]=0&params[offset]=0&params[count]=16&params[v]=5.69) (только надо `offset` изменить на 0). Возможно пользователь в настройках указал не отображать это сообщество. А возможно пользователь является администратором или модератором в группе.

**Comment by rekonchik** [comment]
Жаль, придется после основного прохода запускать ещё сбор данных из сообществ, чтобы получать хоть какое-то приближение.
