### ISSUE TITLE
GetWallExecute puts warnings

### ISSUE THREAD

**Issue by StasSuslov** [Dementiy/vkR#32]
При вызове getWallExecute не происходит возврата списка постов. При этом функция кидает warning типа такого: "Parameter "count" was tuned: 117 per request.". И иногда еще вот такую ошибку: "Error in curl::curl_fetch_memory(url, handle = handle) : Operation was aborted by an application callback".
![2017-11-27_19-15-41](https://user-images.githubusercontent.com/17810032/33276761-7c4be5ca-d3a7-11e7-8764-a383fff33812.png)

**Comment by StasSuslov** [comment]
Все в порядке в версии пакета на GitHub. Тем, кто читает - не качайте с CRAN, качайте отсюда.

**Comment by Dementiy** [comment]
Да, на CRAN старая версия
