### ISSUE TITLE
Invalid request: v (version) is required

### ISSUE THREAD

**Issue by rekonchik** [Dementiy/vkR#36]
https://vk.com/dev/version_update?f=2.%20%D0%A7%D1%82%D0%BE%20%D0%B8%D0%B7%D0%BC%D0%B5%D0%BD%D0%B8%D1%82%D1%81%D1%8F
ВК отказался от версии по умолчанию. Старые функции не работают(

**Comment by yurasik2000** [comment]
+1
Похоже сломались только функции, которые используют execute

**Comment by Dementiy** [comment]
Исправлено
