### ISSUE TITLE
Ошибка при использовании любого метода

### ISSUE THREAD

**Issue by yurasik2000** [Dementiy/vkR#45]
Видимо, что-то поменялось в API в ВК. При вызове любой функции из пакета выдается ошибка:
```
> getGroupsForUsers(1)
Ошибка: VK API request failed
VK error message [8]: Invalid request: v is required. Version param should be passed as "v". "version" param is invalid and not supported.
```
Где этот "version" в коде, я так и не смог найти.

**Comment by Dementiy** [comment]
Версия, которая в репозитории, должна нормально работать. Пакет на CRAN'е не обновлялся.

**Comment by yurasik2000** [comment]
Да, обновился с репозитория и все ОК. Спасибо за вашу работу!

**Comment by Dementiy** [comment]
Обновил пакет на CRAN'е.
