### ISSUE TITLE
Non-standard files/directories found at top level

### ISSUE THREAD

**Issue by tonytonov** [Dementiy/vkR#7]
R CMD CHECK отмечает:

```
checking top-level files ... NOTE
Non-standard files/directories found at top level:
  'examples' 'images'
```

Если эти файлы должны остаться в системе пользователя после установки, то их нужно переместить в `inst`. Если это только для гитхаба, то их надо занести в `.Rbuildignore`.

**Comment by Dementiy** [comment]
Исправлено
