### ISSUE TITLE
Проверки на использование в интерактивном режиме

### ISSUE THREAD

**Issue by tonytonov** [Dementiy/vkR#8]
Как правильно советует @artemklevtsov, перед вызовом `browseURL` и любых других функций, ожидающих ответа пользователя, необходимо проверять, что сессия интерактивна. Это проще всего делать через функцию `interactive`.

Пример: https://github.com/Dementiy/vkR/blob/master/R/auth.R#L35
Это наверняка не единственное такое место.

**Comment by Dementiy** [comment]
Исправил в тех местах, где происходит взаимодействие с пользователем. Авторизацию думаю перепишем с теми правками, которые предложил [@artemklevtsov](https://github.com/artemklevtsov).
